version: "3.8"
networks:
  grpc_network:
    external: true
    name: grpc_network

services:
  nginx:
    container_name: nginx
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - shared-volume:/home/nonroot/.local/lib/python3.13/site-packages/static
    networks:
      - grpc_network

volumes:
  shared-volume:

