version: "3.8"
networks:
  grpc_network:
    name: grpc_network

services:
  fastapi:
    container_name: fastapi-app
    build:
      context: .
      dockerfile: Dockerfile.app
    restart: always
    ports:
      - "8001:8001"
    networks:
      - grpc_network

  grpc_poc_server:
    container_name: grpc-poc-server
    build:
      context: .
      dockerfile: Dockerfile.grpc
    restart: always
    ports:
      - "50053:50053"
    networks:
      - grpc_network

