version: "3.9"
networks:
  grpc_network:
    name: grpc_network
    external: true

services:
  django_grpc:
    environment:
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - GRPC_SERVER=${GRPC_SERVER}
    container_name: django_grpc
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - shared-volume:/home/nonroot/.local/lib/python3.13/site-packages/static
    ports:
      - 8000:8000
    networks:
      - grpc_network

volumes:
  shared-volume:

