version: "3.9"
networks:
  grpc_network:
    name: grpc_network
    external: true

services:
  django_grpc:
    environment:
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - GRPC_SERVER=${GRPC_SERVER}
    container_name: django_grpc
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - shared-volume:/home/nonroot/.local/lib/python3.13/site-packages/static
      # - django_grpc_logs:/app/logs
    ports:
      - 8000:8000
    networks:
      - grpc_network
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-retries: 5
        loki-batch-size: 400
        max-size: "1m" # Rotate logs at 1MB
        max-file: "5" # Keep 5 rotated files

volumes:
  shared-volume:
  django_grpc_logs:

