version: "3.8"
networks:
  grpc_network:
    name: grpc_network
    external: true

services:
  django_grpc:
    environment:
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - GRPC_SERVER=${GRPC_SERVER}
    container_name: django_grpc
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    networks:
      - grpc_network
