version: "3.9"
services:
  grafana:
    build:
      context: ./grafana  # pointing to prometheus directory
      dockerfile: Dockerfile.grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      # - ./grafana:/etc/grafana/provisioning
      # - ./grafana:/etc/grafana/dashboards
      - grafana_data:/var/lib/grafana

  prometheus:
    build:
      context: ./prometheus  # pointing to prometheus directory
      dockerfile: Dockerfile.prometheus
    container_name: prometheus
    restart: unless-stopped
    # command:
    #   - /bin/sh
    #   - -c
    #   - |
    #     envsubst < /etc/prometheus/prometheus.yml.template > /etc/prometheus/prometheus.yml
    #     prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --storage.tsdb.retention.time=7d --storage.tsdb.retention.size=1GB
    ports:
      - 9090:9090
    environment:
      - PROMETHEUS_ADDR=${PROMETHEUS_ADDR}
      - DJANGO_GRPC_ADDR=${DJANGO_GRPC_ADDR}
      - NODE_EXPORTER_ADDR=${NODE_EXPORTER_ADDR}
    volumes:
      - ./prometheus:/etc/prometheus # will create prometheus.yml since we mount volume on here
      - prom_data:/prometheus
    #   - ./prometheus-entrypoint.sh:/prometheus-entrypoint.sh
    # entrypoint: ["/bin/sh", "/prometheus-entrypoint.sh"]

volumes:
  grafana_data:
  prom_data:

